apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: hie-register-openhim-mediator-source
  annotations:
    camel.apache.org/kamelet.support.level: "Stable"
    camel.apache.org/kamelet.icon: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iNjAwcHQiIGhlaWdodD0iMTgwcHQiIHZpZXdCb3g9IjAgMCA2MDAgMTgwIiB2ZXJzaW9uPSIxLjEiPgo8ZyBpZD0ic3VyZmFjZTEiPgo8cGF0aCBzdHlsZT0iIHN0cm9rZTpub25lO2ZpbGwtcnVsZTpub256ZXJvO2ZpbGw6cmdiKDQ4LjczNjU3MiUsNjYuOTYxNjclLDE4LjQzNzE5NSUpO2ZpbGwtb3BhY2l0eToxOyIgZD0iTSA4OS42MjEwOTQgMTM0LjI1IEwgMTQ1LjUzNTE1NiA3Ny43OTY4NzUgTCA2OS42MjEwOTQgMS42NjQwNjIgTCA0OC44NjMyODEgMjIuNDc2NTYyIEwgMTA1LjExMzI4MSA3OC44ODY3MTkgTCA0OS45MDIzNDQgMTM0LjI1IEwgNjkuODI0MjE5IDE1NC4yMzgyODEgTCA4OS42MTcxODggMTM0LjI1IEwgODkuNjIxMDk0IDEzNC4yNSAiLz4KPHBhdGggc3R5bGU9IiBzdHJva2U6bm9uZTtmaWxsLXJ1bGU6bm9uemVybztmaWxsOnJnYigxMi4yMzkwNzUlLDQwLjAwMDkxNiUsMjAuOTg1NDEzJSk7ZmlsbC1vcGFjaXR5OjE7IiBkPSJNIDExOC40ODgyODEgMS42NjQwNjIgTCA5Ny43MjY1NjIgMjIuNDgwNDY5IEwgMTUxLjM2MzI4MSA3Ni4yNjE3MTkgTCAxNTEuMzYzMjgxIDM0LjYzMjgxMiBMIDExOC40ODgyODEgMS42NjQwNjIgIi8+CjxwYXRoIHN0eWxlPSIgc3Ryb2tlOm5vbmU7ZmlsbC1ydWxlOm5vbnplcm87ZmlsbDpyZ2IoMTIuMjM5MDc1JSw0MC4wMDA5MTYlLDIwLjk4NTQxMyUpO2ZpbGwtb3BhY2l0eToxOyIgZD0iTSA5OC43Njk1MzEgMTM0LjI1IEwgMTE4LjY5MTQwNiAxNTQuMjM4MjgxIEwgMTUxLjM2MzI4MSAxMjEuMjQ2MDk0IEwgMTUxLjM2MzI4MSA4MS41MTE3MTkgTCA5OC43Njk1MzEgMTM0LjI1ICIvPgo8cGF0aCBzdHlsZT0iIHN0cm9rZTpub25lO2ZpbGwtcnVsZTpub256ZXJvO2ZpbGw6cmdiKDEyLjIzOTA3NSUsNDAuMDAwOTE2JSwyMC45ODU0MTMlKTtmaWxsLW9wYWNpdHk6MTsiIGQ9Ik0gNTYuMjQ2MDk0IDc4Ljg4NjcxOSBMIDEuMDM5MDYyIDEzNC4yNSBMIDIwLjk2ODc1IDE1NC4yMzgyODEgTCA5Ni42Njc5NjkgNzcuNzkyOTY5IEwgMjAuNzUzOTA2IDEuNjY0MDYyIEwgMCAyMi40ODA0NjkgTCA1Ni4yNDYwOTQgNzguODg2NzE5ICIvPgo8cGF0aCBzdHlsZT0iIHN0cm9rZTpub25lO2ZpbGwtcnVsZTpub256ZXJvO2ZpbGw6cmdiKDE2Ljg3NjIyMSUsNTcuNjE4NzEzJSwyNS40ODM3MDQlKTtmaWxsLW9wYWNpdHk6MTsiIGQ9Ik0gMjAuNzUzOTA2IDEuNjY0MDYyIEwgNDEuNTExNzE5IDIyLjQ4MDQ2OSBMIDQ4Ljg2NzE4OCAyMi40ODA0NjkgTCA2OS42MjEwOTQgMS42NjQwNjIgTCAyMC43NTM5MDYgMS42NjQwNjIgIi8+CjxwYXRoIHN0eWxlPSIgc3Ryb2tlOm5vbmU7ZmlsbC1ydWxlOm5vbnplcm87ZmlsbDpyZ2IoMTYuODc2MjIxJSw1Ny42MTg3MTMlLDI1LjQ4MzcwNCUpO2ZpbGwtb3BhY2l0eToxOyIgZD0iTSA4OS42MjEwOTQgMTM0LjI1IEwgNjkuODI0MjE5IDE1NC4yMzgyODEgTCAxMTguNjk1MzEyIDE1NC4yMzgyODEgTCA5OC43Njk1MzEgMTM0LjI1IEwgODkuNjIxMDk0IDEzNC4yNSAiLz4KPHBhdGggc3R5bGU9IiBzdHJva2U6bm9uZTtmaWxsLXJ1bGU6bm9uemVybztmaWxsOnJnYigyOS40MzQyMDQlLDQzLjIxMTM2NSUsNTIuNjc0ODY2JSk7ZmlsbC1vcGFjaXR5OjE7IiBkPSJNIDg5LjYxNzE4OCAxMzQuMjUgTCA2OS44MjQyMTkgMTU0LjIzODI4MSBMIDg5LjYyMTA5NCAxMzQuMjUgTCA4OS42MTcxODggMTM0LjI1ICIvPgo8cGF0aCBzdHlsZT0iIHN0cm9rZTpub25lO2ZpbGwtcnVsZTpub256ZXJvO2ZpbGw6cmdiKDEyLjIzOTA3NSUsNDAuMDAwOTE2JSwyMC45ODU0MTMlKTtmaWxsLW9wYWNpdHk6MTsiIGQ9Ik0gMTc3LjAxMTcxOSA2MC4zNTU0NjkgTCAxNzcuMDExNzE5IDk1LjM0NzY1NiBMIDE5NC4zOTg0MzggNzcuNzk2ODc1IEwgMTc3LjAxMTcxOSA2MC4zNTU0NjkgIi8+CjxwYXRoIHN0eWxlPSIgc3Ryb2tlOm5vbmU7ZmlsbC1ydWxlOm5vbnplcm87ZmlsbDpyZ2IoMTguNDM1NjY5JSwxOC44OTAzODElLDE5LjI1MDQ4OCUpO2ZpbGwtb3BhY2l0eToxOyIgZD0iTSAxOTcuNjk1MzEyIDI1Ljk0OTIxOSBDIDE5Ny42OTUzMTIgMTguMTY3OTY5IDE5My41MzEyNSAxNC4yNjk1MzEgMTg1LjIxODc1IDE0LjI2OTUzMSBDIDE3Ny4wNDY4NzUgMTQuMjY5NTMxIDE3Mi45Njg3NSAxOC4xNjc5NjkgMTcyLjk2ODc1IDI1Ljk0OTIxOSBMIDE3Mi45Njg3NSAxMjkuOTUzMTI1IEMgMTcyLjk2ODc1IDEzNy45ODA0NjkgMTc3LjA0Njg3NSAxNDIuMDAzOTA2IDE4NS4yMTg3NSAxNDIuMDAzOTA2IEMgMTkzLjUzMTI1IDE0Mi4wMDM5MDYgMTk3LjY5NTMxMiAxMzcuOTgwNDY5IDE5Ny42OTUzMTIgMTI5Ljk1MzEyNSBaIE0gMTU1LjQwNjI1IDI1Ljk0OTIxOSBDIDE1NS40MDYyNSA4LjY0NDUzMSAxNjUuMzQzNzUgMCAxODUuMjE4NzUgMCBDIDIwNS4yNDIxODggMCAyMTUuMjUzOTA2IDguNjQ0NTMxIDIxNS4yNTM5MDYgMjUuOTQ5MjE5IEwgMjE1LjI1MzkwNiAxMjkuOTUzMTI1IEMgMjE1LjI1MzkwNiAxNDcuMjUgMjA1LjI0MjE4OCAxNTUuODk4NDM4IDE4NS4yMTg3NSAxNTUuODk4NDM4IEMgMTY1LjM0Mzc1IDE1NS44OTg0MzggMTU1LjQwNjI1IDE0Ny4yNSAxNTUuNDA2MjUgMTI5Ljk1MzEyNSBMIDE1NS40MDYyNSAyNS45NDkyMTkgIi8+CjxwYXRoIHN0eWxlPSIgc3Ryb2tlOm5vbmU7ZmlsbC1ydWxlOm5vbnplcm87ZmlsbDpyZ2IoMTguNDM1NjY5JSwxOC44OTAzODElLDE5LjI1MDQ4OCUpO2ZpbGwtb3BhY2l0eToxOyIgZD0iTSAyNjMuNzczNDM4IDYxLjUzOTA2MiBDIDI2My43NzM0MzggNTcuOTU3MDMxIDI2Mi45Njg3NSA1NS40NjA5MzggMjYxLjM1MTU2MiA1NC4wMzkwNjIgQyAyNTkuNzMwNDY5IDUyLjYxNzE4OCAyNTcuMTQ0NTMxIDUxLjkwNjI1IDI1My42MDU0NjkgNTEuOTA2MjUgQyAyNTAuOTg4MjgxIDUxLjkwNjI1IDI0OC41NjI1IDUyLjUyNzM0NCAyNDYuMzI0MjE5IDUzLjc1MzkwNiBDIDI0NC4wOTc2NTYgNTQuOTkyMTg4IDI0Mi40MzM1OTQgNTYuODQ3NjU2IDI0MS4zNjMyODEgNTkuMzE2NDA2IEwgMjQxLjM2MzI4MSAxMzUuNjk1MzEyIEMgMjQyLjQzMzU5NCAxMzguMTY3OTY5IDI0NC4wOTc2NTYgMTQwLjAyMzQzOCAyNDYuMzI0MjE5IDE0MS4yNTM5MDYgQyAyNDguNTYyNSAxNDIuNDkyMTg4IDI1MC45ODgyODEgMTQzLjEwOTM3NSAyNTMuNjA1NDY5IDE0My4xMDkzNzUgQyAyNTcuMTQ0NTMxIDE0My4xMDkzNzUgMjU5LjczMDQ2OSAxNDIuNDAyMzQ0IDI2MS4zNTE1NjIgMTQwLjk3MjY1NiBDIDI2Mi45Njg3NSAxMzkuNTU4NTk0IDI2My43NzM0MzggMTM3LjE3NTc4MSAyNjMuNzczNDM4IDEzMy44MzU5MzggWiBNIDIyNS40MTQwNjIgMTgwIEwgMjI1LjQxNDA2MiAzOS40ODQzNzUgTCAyMzguODI4MTI1IDM5LjQ4NDM3NSBDIDIzOS4yODUxNTYgNDIuMzI4MTI1IDIzOS41MTU2MjUgNDUuMjM0Mzc1IDIzOS41MTU2MjUgNDguMTk1MzEyIEMgMjQxLjIxMDkzOCA0NC45ODgyODEgMjQzLjU4OTg0NCA0Mi41MzkwNjIgMjQ2LjY3NTc4MSA0MC44NzEwOTQgQyAyNDkuNzYxNzE5IDM5LjIxMDkzOCAyNTMuOTE0MDYyIDM4LjM2NzE4OCAyNTkuMTUyMzQ0IDM4LjM2NzE4OCBDIDI2NS43NzM0MzggMzguMzY3MTg4IDI3MC44MjQyMTkgNDAuMTA1NDY5IDI3NC4yODkwNjIgNDMuNTYyNSBDIDI3Ny43NTc4MTIgNDcuMDE5NTMxIDI3OS40ODgyODEgNTIuNDU3MDMxIDI3OS40ODgyODEgNTkuODc1IEwgMjc5LjQ4ODI4MSAxMzQuOTUzMTI1IEMgMjc5LjQ4ODI4MSAxNDIuNzM4MjgxIDI3Ny44NzEwOTQgMTQ4LjE3NTc4MSAyNzQuNjM2NzE5IDE1MS4yNjk1MzEgQyAyNzEuMzk4NDM4IDE1NC4zNTU0NjkgMjY2LjA4OTg0NCAxNTUuOTAyMzQ0IDI1OC42OTE0MDYgMTU1LjkwMjM0NCBDIDI1NC44MzU5MzggMTU1LjkwMjM0NCAyNTEuNDE3OTY5IDE1NS4yNTM5MDYgMjQ4LjQxMDE1NiAxNTMuOTQ5MjE5IEMgMjQ1LjQwMjM0NCAxNTIuNjYwMTU2IDI0My4wNTA3ODEgMTUwLjk1MzEyNSAyNDEuMzYzMjgxIDE0OC44NTU0NjkgTCAyNDEuMzYzMjgxIDE4MCBMIDIyNS40MTQwNjIgMTgwICIvPgo8cGF0aCBzdHlsZT0iIHN0cm9rZTpub25lO2ZpbGwtcnVsZTpub256ZXJvO2ZpbGw6cmdiKDE4LjQzNTY2OSUsMTguODkwMzgxJSwxOS4yNTA0ODglKTtmaWxsLW9wYWNpdHk6MTsiIGQ9Ik0gMzI0LjQzMzU5NCA2MS4xNzE4NzUgQyAzMjQuNDMzNTk0IDU0LjM3ODkwNiAzMjAuODg2NzE5IDUwLjk4MDQ2OSAzMTMuODA0Njg4IDUwLjk4MDQ2OSBDIDMwNy4xNzk2ODggNTAuOTgwNDY5IDMwMy44NjcxODggNTQuMzc4OTA2IDMwMy44NjcxODggNjEuMTcxODc1IEwgMzAzLjg2NzE4OCA4OC43OTY4NzUgTCAzMjQuNDMzNTk0IDg4Ljc5Njg3NSBaIE0gMzI0LjQzMzU5NCAxMDcuNTE5NTMxIEwgMzM5LjQ1NzAzMSAxMDcuNTE5NTMxIEwgMzM5LjQ1NzAzMSAxMzIuNzMwNDY5IEMgMzM5LjQ1NzAzMSAxNDguMTc1NzgxIDMzMC45MDIzNDQgMTU1Ljg5NDUzMSAzMTMuODA0Njg4IDE1NS44OTQ1MzEgQyAyOTcuMzIwMzEyIDE1NS44OTQ1MzEgMjg5LjA3NDIxOSAxNDguMTc1NzgxIDI4OS4wNzQyMTkgMTMyLjczMDQ2OSBMIDI4OS4wNzQyMTkgNjEuMTcxODc1IEMgMjg5LjA3NDIxOSA1My4zODI4MTIgMjkxLjE5MTQwNiA0Ny41MjM0MzggMjk1LjQzMzU5NCA0My41NjI1IEMgMjk5LjY2Nzk2OSAzOS42MDkzNzUgMzA1Ljc4OTA2MiAzNy42Mjg5MDYgMzEzLjgwNDY4OCAzNy42Mjg5MDYgQyAzMzAuOTAyMzQ0IDM3LjYyODkwNiAzMzkuNDU3MDMxIDQ1LjQ3NjU2MiAzMzkuNDU3MDMxIDYxLjE3MTg3NSBMIDMzOS40NTcwMzEgOTguMDU4NTk0IEwgMzAzLjg2NzE4OCA5OC4wNTg1OTQgTCAzMDMuODY3MTg4IDEzMi43MzA0NjkgQyAzMDMuODY3MTg4IDEzOS41MzEyNSAzMDcuMTc5Njg4IDE0Mi45MjE4NzUgMzEzLjgwNDY4OCAxNDIuOTIxODc1IEMgMzIwLjg4NjcxOSAxNDIuOTIxODc1IDMyNC40MzM1OTQgMTM5LjUzMTI1IDMyNC40MzM1OTQgMTMyLjczMDQ2OSBMIDMyNC40MzM1OTQgMTA3LjUxOTUzMSAiLz4KPHBhdGggc3R5bGU9IiBzdHJva2U6bm9uZTtmaWxsLXJ1bGU6bm9uemVybztmaWxsOnJnYigxOC40MzU2NjklLDE4Ljg5MDM4MSUsMTkuMjUwNDg4JSk7ZmlsbC1vcGFjaXR5OjE7IiBkPSJNIDM4Ny4wMDM5MDYgMTU0LjIzNDM3NSBMIDM4Ny4wMDM5MDYgNTkuNTA3ODEyIEMgMzg3LjAwMzkwNiA1Ni4xNjQwNjIgMzg2LjMwODU5NCA1My43OTI5NjkgMzg0LjkyNTc4MSA1Mi4zNjcxODggQyAzODMuNTM5MDYyIDUwLjk0NTMxMiAzODEuMTUyMzQ0IDUwLjIzNDM3NSAzNzcuNzYxNzE5IDUwLjIzNDM3NSBDIDM3NS40NTMxMjUgNTAuMjM0Mzc1IDM3My4xNDA2MjUgNTAuNzg5MDYyIDM3MC44MjgxMjUgNTEuOTA2MjUgQyAzNjguNTE5NTMxIDUzLjAxOTUzMSAzNjYuNzUgNTQuODA4NTk0IDM2NS41MTk1MzEgNTcuMjc3MzQ0IEwgMzY1LjUxOTUzMSAxNTQuMjM0Mzc1IEwgMzQ5LjU3NDIxOSAxNTQuMjM0Mzc1IEwgMzQ5LjU3NDIxOSAzOS40ODQzNzUgTCAzNjIuOTc2NTYyIDM5LjQ4NDM3NSBDIDM2My40Mzc1IDQyLjMyODEyNSAzNjMuNjY3OTY5IDQ1LjIzNDM3NSAzNjMuNjY3OTY5IDQ4LjE5NTMxMiBDIDM2NS44MTY0MDYgNDQuOTg4MjgxIDM2OC42NzU3ODEgNDIuNDE0MDYyIDM3Mi4yMTQ4NDQgNDAuNTAzOTA2IEMgMzc1Ljc1NzgxMiAzOC41ODU5MzggMzc5Ljc1NzgxMiAzNy42Mjg5MDYgMzg0LjIzMDQ2OSAzNy42Mjg5MDYgQyAzOTAuNzAzMTI1IDM3LjYyODkwNiAzOTUuNDQxNDA2IDM5LjMwMDc4MSAzOTguNDQ1MzEyIDQyLjYzNjcxOSBDIDQwMS40NDkyMTkgNDUuOTcyNjU2IDQwMi45NDUzMTIgNTEuMzUxNTYyIDQwMi45NDUzMTIgNTguNzYxNzE5IEwgNDAyLjk0NTMxMiAxNTQuMjM0Mzc1IEwgMzg3LjAwMzkwNiAxNTQuMjM0Mzc1ICIvPgo8cGF0aCBzdHlsZT0iIHN0cm9rZTpub25lO2ZpbGwtcnVsZTpub256ZXJvO2ZpbGw6cmdiKDEyLjIzOTA3NSUsNDAuMDAwOTE2JSwyMC45ODU0MTMlKTtmaWxsLW9wYWNpdHk6MTsiIGQ9Ik0gNDU1LjQwMjM0NCAxNTQuMjM0Mzc1IEwgNDU1LjQwMjM0NCA4My42MDE1NjIgTCA0MzAuOTAyMzQ0IDgzLjYwMTU2MiBMIDQzMC45MDIzNDQgMTU0LjIzNDM3NSBMIDQxMy4zNDc2NTYgMTU0LjIzNDM3NSBMIDQxMy4zNDc2NTYgMS42NjQwNjIgTCA0MzAuOTAyMzQ0IDEuNjY0MDYyIEwgNDMwLjkwMjM0NCA2OS43MDMxMjUgTCA0NTUuNDAyMzQ0IDY5LjcwMzEyNSBMIDQ1NS40MDIzNDQgMS42NjQwNjIgTCA0NzIuOTYwOTM4IDEuNjY0MDYyIEwgNDcyLjk2MDkzOCAxNTQuMjM0Mzc1IEwgNDU1LjQwMjM0NCAxNTQuMjM0Mzc1ICIvPgo8cGF0aCBzdHlsZT0iIHN0cm9rZTpub25lO2ZpbGwtcnVsZTpub256ZXJvO2ZpbGw6cmdiKDEyLjIzOTA3NSUsNDAuMDAwOTE2JSwyMC45ODU0MTMlKTtmaWxsLW9wYWNpdHk6MTsiIGQ9Ik0gNDgzLjgzOTg0NCAxNTQuMjMwNDY5IEwgNTAxLjQwMjM0NCAxNTQuMjMwNDY5IEwgNTAxLjQwMjM0NCAxLjY2MDE1NiBMIDQ4My44Mzk4NDQgMS42NjAxNTYgWiBNIDQ4My44Mzk4NDQgMTU0LjIzMDQ2OSAiLz4KPHBhdGggc3R5bGU9IiBzdHJva2U6bm9uZTtmaWxsLXJ1bGU6bm9uemVybztmaWxsOnJnYigxMi4yMzkwNzUlLDQwLjAwMDkxNiUsMjAuOTg1NDEzJSk7ZmlsbC1vcGFjaXR5OjE7IiBkPSJNIDU4My41OTM3NSAxNTQuMjM0Mzc1IEwgNTgzLjU5Mzc1IDEwOC4wNzAzMTIgQyA1ODMuNTkzNzUgOTYuODMyMDMxIDU4My42MzI4MTIgODUuODI4MTI1IDU4My43MDcwMzEgNzUuMDc0MjE5IEMgNTgzLjc4OTA2MiA2NC4zMjQyMTkgNTgzLjkwMjM0NCA1My4zMjgxMjUgNTg0LjA1NDY4OCA0Mi4wNzgxMjUgTCA1NjMuNDkyMTg4IDE1NC4yMzQzNzUgTCA1NDguMDExNzE5IDE1NC4yMzQzNzUgTCA1MjcuNjc1NzgxIDQyLjA3ODEyNSBDIDUyNy44MjAzMTIgNTMuMzI4MTI1IDUyNy45NDE0MDYgNjQuMzI0MjE5IDUyOC4wMTk1MzEgNzUuMDc0MjE5IEMgNTI4LjA5NzY1NiA4NS44MjgxMjUgNTI4LjE0MDYyNSA5Ni44MzIwMzEgNTI4LjE0MDYyNSAxMDguMDcwMzEyIEwgNTI4LjE0MDYyNSAxNTQuMjM0Mzc1IEwgNTExLjk2MDkzOCAxNTQuMjM0Mzc1IEwgNTExLjk2MDkzOCAxLjY2NDA2MiBMIDUzNS41MzEyNSAxLjY2NDA2MiBMIDU1NS42MzY3MTkgMTIwLjg2MzI4MSBMIDU3NS43NDIxODggMS42NjQwNjIgTCA2MDAgMS42NjQwNjIgTCA2MDAgMTU0LjIzNDM3NSBMIDU4My41OTM3NSAxNTQuMjM0Mzc1ICIvPgo8L2c+Cjwvc3ZnPgo="
    camel.apache.org/provider: "HISP Centre"
    camel.apache.org/kamelet.group: "HIE OpenHim"
    camel.apache.org/kamelet.namespace: "HIE"
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: Register OpenHIM Mediator
    description: |-
      Register a mediator with OpenHIM.
    required:
      - openHimUrl
      - openHimUsername
      - openHimPassword
    properties:
      openHimUrl:
        title: OpenHIM URL
        type: string
      openHimUsername:
        title: OpenHIM Username
        type: string
        x-descriptors:
          - urn:camel:group:credentials
      openHimPassword:
        title: OpenHIM Password
        type: string
        format: password
        x-descriptors:
          - urn:camel:group:credentials
      httpClientConfigurer:
        title: HTTP Client Configurer
        type: string
        example: "#selfSignedHttpClientConfigurer"
      mediatorUrn:
        title: Mediator URN
        type: string
        default: urn:mediator:camel-hie-mediator
      mediatorVersion:
        title: Mediator Version
        type: string
        default: 1.0.0
      mediatorName:
        title: Mediator Name
        type: string
        default: Camel HIE Mediator
      defaultChannelName:
        title: Default Channel Name
        type: string
        default: camel-hie-channel
      defaultChannelMethods:
        title: Default Channel Name
        type: array
        items:
          type: string
        default: DELETE, GET, PATCH, POST, PUT
      defaultChannelUrlPattern:
        title: Default Channel URL Pattern
        type: string
        default: "^/"
      defaultChannelAuthType:
        title: Default Channel Auth Type
        type: string
        default: public
      defaultChannelRouteName:
        title: Default Channel Route Name
        type: string
        default: Camel HIE Route
      defaultChannelRouteHost:
        title: Default Channel Route Host
        type: string
        default: localhost
      defaultChannelRoutePort:
        title: Default Channel Route Port
        type: string
        default: 9070
      defaultChannelRoutePath:
        title: Default Channel Route Path
        type: string
        default: "/"
      defaultChannelRoutePrimary:
        title: Default Channel Route Primary
        type: boolean
        default: true
      defaultChannelRouteSecured:
        title: Default Channel Route Secured
        type: boolean
        default: false
      endpointName:
        title: Endpoint Name
        type: string
        default: Camel HIE Endpoint
      endpointType:
        title: Endpoint Type
        type: string
        default: http
      endpointSecured:
        title: Endpoint Secured
        type: boolean
        default: false
      endpointHost:
        title: Endpoint Host
        type: string
        default: localhost
      endpointPort:
        title: Endpoint Port
        type: string
        default: 9070
      endpointStatus:
        title: Endpoint Status
        type: string
        enum: ["enabled", "disabled"]
        default: enabled
      endpointPath:
        title: Endpoint Path
        type: string
        default: "/"
  template:
    beans:
      - name: routePropsToExchangePropsProcessor
        type: "#class:org.hisp.hieboot.camel.processor.RoutePropsToExchangePropsProcessor"
    from:
      uri: timer://registerOpenHimMediator?repeatCount=1
      steps:
        - process:
            ref: "{{routePropsToExchangePropsProcessor}}"
        - transform:
            datasonnet:
              source: null
              expression: resource:classpath:openhim/mediator-config.ds
              resultType: java.lang.String
              bodyMediaType: application/x-java-object
              outputMediaType: application/json
        - setHeader:
            name: Content-Type
            constant: "application/json"
        - log: "Registering [{{mediatorUrn}}] mediator with OpenHIM..."
        - to:
            uri: "{{openHimUrl}}/mediators"
            parameters:
              httpClientConfigurer: "{{?httpClientConfigurer}}"
              authUsername: "{{openHimUsername}}"
              authPassword: "{{openHimPassword}}"
              authenticationPreemptive: true
              httpMethod: POST
        - log: "Registered [{{mediatorUrn}}] mediator with OpenHIM"
        - to: "kamelet:sink"
