apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: hie-fail-replay-checkpoint-action
  annotations:
    camel.apache.org/kamelet.support.level: Stable
    camel.apache.org/provider: HISP Centre
    camel.apache.org/kamelet.group: HIE Replay
    camel.apache.org/kamelet.namespace: HIE
  labels:
    camel.apache.org/kamelet.type: action
spec:
  definition:
    title: Fail Replay Checkpoint Action
    description: |-
      Marks replay checkpoint as failed.
    properties:
      replayChannelName:
        title: Replay Channel Name
        type: string
        default: replay-{{routeId}}
  dataTypes:
    in:
      headers:
        errorMessage:
          title: Error Message
          type: string
  template:
    beans:
      - name: failCheckpointProcessor
        type: "#class:org.hisp.hieboot.camel.processor.replay.FailCheckpointProcessor"
    route:
      from:
        uri: kamelet:source
        steps:
          - process:
              ref: "{{failCheckpointProcessor}}"
          - to: kamelet:sink
