name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - run: mvn -B package
  generate_kamelet_catalog:
    if: github.repository == 'dhis2/camel-hie-boot' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: "Import GPG key"
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.AUTODOC_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.AUTODOC_BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm run generate
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: generate Kamelet catalog [skip ci]'
          file_pattern: 'kamelet-catalog.md'
          commit_author: "Auto-Doc Bot <${{ steps.import-gpg.outputs.email }}>"
          commit_user_name: auto-doc-bot
          commit_user_email: ${{ steps.import-gpg.outputs.email }}
